spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/library?useUnicode=yes&characterEncoding=UTF-8
#    username: libraryUser
#    password: libraryPass
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always

  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library

#  jpa:
#    show-sql: true

  messages:
    encoding: UTF-8
    basename: bundle